[package]
name = "thin_main_loop"
version = "0.1.0"
authors = ["David Henningsson <diwic@ubuntu.com>"]
edition = "2018"

[target.'cfg(unix)'.dependencies]
glib-sys = "0.7"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winuser", "libloaderapi", "std"] }